language: python
sudo: false
notifications:
  email:
    on_success: never
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install -r requirements-dev.txt
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
